# Movie Recommender System Project

In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
movies = movies.merge(credits, on='title')

In [6]:
print(movies.shape)
movies.head()

(4809, 23)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

# Featue Engineeing

In [7]:
# select the important featues by intuition:
movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']].copy()

# Preprocessing
1. Removing missing values

In [8]:

movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [9]:
movies.dropna(inplace =True)

2. check and remove the duplicates

In [10]:
movies.duplicated().sum()

0

3. Formating the data. 
From the features which are in the format of **string of list of dictionariers**, take the important list of values only.

In [11]:
# to convert the string of list to only list:
import ast

In [12]:
def convert(obj):
    list = []
    for i  in ast.literal_eval(obj):
        list.append(i['name'])
    return list

In [13]:
movies['genres'] = movies['genres'].apply(convert)

In [14]:
# convert the keywords feature  like genres feature:
movies['keywords'] = movies['keywords'].apply(convert)

In [15]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [16]:
 # "For the 'cast' data, keep only the first 3 actor dictionaries since they correspond to the main starring roles."
# And from those dictionaries take out only the real names of actors and make list of those 3 names

def convert3(obj):
    list = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            list.append(i['name'])
            counter+=1
        else:
            break
    return list

In [17]:
movies['cast'] = movies['cast'].apply(convert3)

In [18]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

From the crew feature extracting only the director name , which we are interested in:
1. take out the dictionary in which name is director.
2. take out the value of name key from that dictionary.

In [19]:
def fetch_director(obj):
    list = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            list.append(i['name'])
            break
    return list

In [20]:
movies['crew']  = movies['crew'].apply(fetch_director)

In [21]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

Overview feature is a string, we need to convert it into list of words so that it can be concatenated with the others in the later stage.

In [22]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [23]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

Strip the spaces between the words of a single name

In [24]:
for feature in ['genres', 'keywords', 'cast', 'crew']:
    movies[feature] = movies[feature].apply(lambda x: [i.replace(" ", "") for i in x])

In [25]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

Now create a new feature named tags which will be the concatenaton of overview, genres, keywords, cast, crew

In [26]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [27]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

Create a new_df with only interested features

In [28]:
new_df = movies[['movie_id', 'title', 'tags']].copy()

In [29]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

Make a single string out of the list in the tags featue:

In [30]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [31]:
# convert the tags feature in lowercase
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [32]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

## model training

Apply stemming to the tags feature to remove related words like loved, loving, loved = love etc

In [33]:
import nltk

In [34]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [35]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return ' '.join(y)

In [36]:
new_df['tags'] = new_df['tags'].apply(stem)

In [37]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

Use count_vectorizer of scikit learn. 
What it does:
1. Makes a bag of words from all the rows of the selected column and returns their frequency appearance.
2. Returns the top frequent words with 'max_features' after removing stop words with 'stop_words='english'.
3. Finally checks the appearance of each word in a row and returns their frequency, which makes the vector of that row.

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=10000, stop_words='english')

In [39]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [40]:
vectors.shape

(4806, 10000)

In [41]:
# we can get the 5000 words which the cv object returned:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zooeydeschanel', 'zookeep', 'zoëkravitz'],
      dtype=object)

In [42]:
len(cv.get_feature_names_out())

10000

Now we need to find the similarity between the vectors, we will count the cosine distance (angle) between them.

In [43]:
from sklearn.metrics.pairwise import cosine_similarity

In [44]:
similarity = cosine_similarity(vectors)

In [45]:
similarity.shape

(4806, 4806)

Make a function (recommender) which will return top n similar movies from the similarity matrix:
Note: This top n similar movies =(sorting) method will shuffle the movies, therefore we need to append index with movie so that where it goes in sorting, it goes with index intact.
 1. Get the index of the movie of which trying to return the similar movies from the new_df.
 2. Get the similarity array for that particular index from the similarity matrix. This similarity array is the similarity of all the movies with the particular index movie.
 3. Sort the array with every values index intact(tuple of index and similarity value) in reverse order to  get the top n values ( which is the index and the similarity value ).
 4. Take out the index values and match with the title feature of the new_df dataframe.

In [46]:
def recommender(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]  # key is for sorting the tuple on second value and [1:6] is for getting top 5 movies, since 0 is itself.

    rec_list = []
    for i in movies_list:# to get the only index of the movies and match them with title and get movie names
        rec = new_df.iloc[i[0]].title
        rec_list.append(rec)
    return rec_list

In [47]:
recommender('Batman Begins')

['The Dark Knight', 'Batman', 'Batman', 'The Dark Knight Rises', 'Rockaway']

## Using Nearest Neighbors algorithm

In [48]:
from sklearn.neighbors import NearestNeighbors

model = NearestNeighbors(n_neighbors=6, metric='cosine')
model.fit(vectors)

NearestNeighbors(metric='cosine', n_neighbors=6)

In [49]:
def recommend_movies(movie_title):
    # Find movie index
    movie_index = new_df[new_df['title'] == movie_title].index[0]

    movie_vector = vectors[movie_index].reshape(1, -1)
    # Get nearest neighbors using KNN
    distances, indices = model.kneighbors(movie_vector)
    
    # Return top 5 similar movies (excluding itself)
    similar_movies = new_df.iloc[indices[0][1:6]]['title']
    return similar_movies

In [50]:
recommend_movies('Batman Begins')

65            The Dark Knight
1361                   Batman
1360                   Batman
3       The Dark Knight Rises
4148                 Rockaway
Name: title, dtype: object

In [51]:
for i in range(len(indices)):
    print(pivot_table.index[indices[i]])

NameError: name 'indices' is not defined

## Evaluation:
### use diversity score metric:
    The ideal score depends on your specific goals:
    
        For discovery-focused systems (where you want to surprise users):
    
            Target: 0.1-0.3
    
            Example: "If you liked The Dark Knight, try this documentary about Batman's history"
    
        For precision-focused systems (where similarity is key):
    
            Target: 0.4-0.6
    
            Example: "If you liked The Dark Knight, try Batman Begins"
    
        Balanced systems:
    
            Target: 0.2-0.4

Real-World Examples:
| Platform | Strategy                          | Diversity Level       |
|----------|-----------------------------------|-----------------------|
| Netflix  | "Because you watched X" + "Trending" | Moderate (0.3–0.5)    |
| Spotify  | "Discover Weekly" playlists       | High (0.1–0.3)        |
| Amazon   | "Frequently bought together"      | Low (0.6–0.8)         |

In [ ]:

movie_indices = {title: idx for idx, title in enumerate(new_df['title'])}

In [ ]:
def calculate_diversity_bow(recommendations, count_vectorizer, movie_indices, bow_matrix):
    """
    Calculate recommendation diversity using Bag of Words vectors
    
    Parameters:
    - recommendations: List of recommended movie titles
    - count_vectorizer: Your fitted CountVectorizer instance
    - movie_indices: Dictionary mapping movie titles to matrix indices
    - bow_matrix: Your bag-of-words matrix from CountVectorizer
    
    Returns:
    - Diversity score (lower = more diverse)
    """
    # Get indices for recommended movies
    rec_indices = [movie_indices[title] for title in recommendations]
    
    # Extract BOW vectors for these movies
    rec_vectors = bow_matrix[rec_indices]
    
    # Calculate pairwise cosine similarities
    similarity_matrix = cosine_similarity(rec_vectors)
    
    # Zero out diagonal (self-similarity)
    np.fill_diagonal(similarity_matrix, 0)
    
    # Return average similarity between different movies
    return similarity_matrix.mean()

# Example usage:
diversity_scores = []
  # Your sample movies

# Assuming you have:
# - count_vect: Your fitted CountVectorizer
# - bow_matrix: The output from count_vect.fit_transform()
# - movie_indices: Dictionary like {'The Dark Knight': 0, 'Inception': 1, ...}

for movie in new_df['title'].sample(100):
    recs = recommender(movie)
    diversity = calculate_diversity_bow(recs, cv, movie_indices, vectors)
    diversity_scores.append(diversity)
    # print(f"Recommendations for {movie}:")
    # print(recs)
    # print(f"Diversity score: {diversity:.3f}\n")

print(f"\nAverage diversity across all samples: {np.mean(diversity_scores):.3f}")
print("(Lower values indicate more diverse recommendations)")

## Another way of doing getting the recommendations:

In [ ]:
movie_title = {title: idx for title, idx in enumerate(new_df['title'])}

In [ ]:
 from sklearn.metrics.pairwise import pairwise_distances

In [ ]:

def brute_force_nearest(title, all_vectors = vectors, n=5, metric='cosine'):
    query_vector = vectors[movie_indices[title]]
    query_2d = np.reshape(query_vector, (1, -1))
    distances = pairwise_distances(query_2d, all_vectors, metric=metric).flatten()
    nearest_indices = np.argsort(distances)[:6]  # For cosine similarity, lower = closer
    list = []
    for index in nearest_indices:
        list.append(movie_title[index])
    return list

In [ ]:
brute_force_nearest('Batman Begins')

In [ ]:
diversity_scores = []
  # Your sample movies

# Assuming you have:
# - count_vect: Your fitted CountVectorizer
# - bow_matrix: The output from count_vect.fit_transform()
# - movie_indices: Dictionary like {'The Dark Knight': 0, 'Inception': 1, ...}

for movie in new_df['title'].sample(100):
    recs = brute_force_nearest(movie)
    diversity = calculate_diversity_bow(recs, cv, movie_indices, vectors)
    diversity_scores.append(diversity)
    # print(f"Recommendations for {movie}:")
    # print(recs)
    # print(f"Diversity score: {diversity:.3f}\n")

print(f"\nAverage diversity across all samples: {np.mean(diversity_scores):.3f}")
print("(Lower values indicate more diverse recommendations)")